env=qa
browser=chrome

qa.studentapply.url=https://suadm-stg.suh.edu.in/student/apply-now
qa.studentenquiry.url=https://suadm-stg.suh.edu.in/enquiry
qa.student.mobile=9547720146
qa.student.email=Omkar1778217865098@yopmail.com
qa.student.password=Sree@123

qa.admin.url=https://stg.1sports.app/login
qa.admin.email=support@yopmail.com
qa.admin.password=Sree@123