# environment
env=qa
browser=chrome
adminurl=https://stg.1sports.app/login
studentUrl=https://suadm-stg.suh.edu.in/student/apply-now
adminemail=support@yopmail.com
adminpwd=Sree@123

# qa urls
qa.url=https://qa.myapp.com
qa.username=qa_user
qa.password=qa_pass

# uat urls
uat.url=https://uat.myapp.com
uat.username=uat_user
uat.password=uat_pass